### ISSUE TITLE
Org and Space Not Updated

### ISSUE THREAD

**Issue by stevewallecs** [ECSTeam/cloudfoundry-top-plugin#5]
The Org List/Stats view does not reflect newly created orgs. That is, if cf top is running and a new org is created, it does not appear in the view. A restart of cf top does cause the org to display.

**Comment by kkellner** [comment]
cf top works by listening for events in the firehose.   Because new application deployments cause firehose events (e.g., staging , container creation, etc), cf top can keep itself updated on new apps.  However, when an org or space is created, there is no firehose event.   Because of this, there is no way for cf top to know its data is outdated.    You can press 'r' to reload all metadata but a user would need to know that the data is outdated.

The only thing that would be possible (and likely doesn't happen now) is if a new application is deployed to a new org and/or space and that org/space metadata is loaded, this could trigger a reload of that org/space metadata.  Right now I would guess that the new org/space would display the GUID on the UI.

**Comment by kkellner** [comment]
New enhancement!   When a new Org or Space is created (or renamed), cf top now recognizes the change and load/reloads the metadata for the given item.   The end result is the UI correctly reflects the names of the orgs and spaces.
